library(testthat, quietly=TRUE)
source("R/myfunctions.R")

test_that("Verify type in sample info file", {
  expect_true(is.character(read_sample_info()$id))
  expect_true(is.numeric(read_sample_info()$age14C))
  expect_true(is.numeric(read_sample_info()$age14Cerror))
  expect_true(is.numeric(read_sample_info()$ageBCAD))
  expect_true(is.numeric(read_sample_info()$coverage))
  # expect_true(is.logical(read_sample_info()$is_modern))
  # expect_true(is.logical(read_sample_info()$is_ancient))
  # expect_true(is.logical(read_sample_info()$is_dr))
  expect_true(is.numeric(read_sample_info()$total_ancient))
  expect_true(is.numeric(read_sample_info()$size))
  expect_true(is.numeric(read_sample_info()$t0))
})
