# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI in conda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: false
        miniconda-version: 'latest'
        python-version: ${{ matrix.python-version }}
        environment-file: timeadapt.yml
        activate-environment: timeadapt
    - name: Test with pytest
      shell: pwsh
      run: |
          pytest scripts/timeadapt.py
          pytest scripts/test_timeadapt.py
