# This is a basic workflow to help you get started with Actions

name: run-tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up R 3.6.1
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.1'
      - name: Install dependencies
        shell: Rscript {0}
        run: |
          install.packages(c("rcarbon","testthat","argparser"))

      - name: Testthat
        shell: Rscript {0}
        run: |
          library(testthat)
          test_file("tests/testthat/test_myfunctions.R",reporter="fail")
          
          
